### ISSUE TITLE
Error message when trying to update

### ISSUE THREAD

**Issue by FaithOfSin** [LoafOrc/loaforcsSoundAPI#14]
Hello!

I just saw the update to 1.1.5 and there is an error message popping up, I can´t update the mod at all. (see picture)
I followed the path mentioned in the error and there is no "6.0.0" folder for me.
Only dependant is Lethal Resonance. (see picture)

Here is the full modpack code I am using: 01905db4-f58a-95ad-5f9c-87b378846c43
I am using Thunderstore.
I also tried reinstalling bepin because I thought it maybe didn´t make a necessary folder last time, but nothing changed.

Thank you in advance!

![SoundAPI Error](https://github.com/LoafOrc/loaforcsSoundAPI/assets/160816582/1ebb2075-9bc9-4e42-9e76-d290a01ff23c)
![SoundAPI Depen](https://github.com/LoafOrc/loaforcsSoundAPI/assets/160816582/a1524d21-92b6-4fbf-999d-e014702ede43)

**Comment by LoafOrc** [comment]
fixed in 1.1.6
