### ISSUE TITLE
NullReferenceException at AudioSourcePatch.ProcessName

### ISSUE THREAD

**Issue by NiroDev** [LoafOrc/loaforcsSoundAPI#4]
Hey,
in my mod LittleCompany i'm adding and removing a grabbableObject from the player at runtime. That can lead to an exception in the method from the title, likely the audioSource.gameObject part. Could you add an additional condition for it using "?" behind audioSource or by adding an if(audioSource.gameObject != null) please?
I'll try to look into the issue from our side aswell and try to ensure that any audio is stopped when the object gets removed.

Greets, Niro

**Comment by LoafOrc** [comment]
oh god thats a little bit cooked but could be doable

**Comment by LoafOrc** [comment]
should be fixed in 1.0.0 release
https://github.com/LoafOrc/loaforcsSoundAPI/pull/8/commits/225c0f39e254183e81c68c328bb1612a0ad5aadc
