### ISSUE TITLE
LethalResonance/loaforc api missing referenced scripts

### ISSUE THREAD

**Issue by Catpyre** [LoafOrc/loaforcsSoundAPI#6]
So everytime the game is launched I get this string of referenced scripts being missing? I also find that sometimes some sounds just dont play the Lethal Resonance sounds? Lethal Resonance also takes quite a bit of time to load due to it.

> [Info   :me.loaforc.soundapi] Loaded LethalResonance(non-startup) in 11387ms.
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Mesh') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'EntranceTeleportB') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'VentEntrance') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'IndirectLight') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube (1)') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Mesh (1)') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube (1)') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Boombox') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'EntranceTeleportA') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'BigDoor') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'SteelDoorMapModel') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'LungApparatusTurnedOff') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube (1)') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'CollisionMesh') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Mesh') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube (1)') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'TurretContainer') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!

**Comment by LoafOrc** [comment]
could you provide a full mod list? this seems like some mod is somehow unregistering one of the internal helper behaviours of soundapi

**Comment by Catpyre** [comment]
From time to time il lalso get the error about advanced company though i uninstalled AC awhile ago. Here's the full mod list though

> 2018-LC_API-3.4.5
BepInEx-BepInExPack-5.4.2100
monkes_mods-JumpDelayPatch-1.0.1
Renegades-WalkieUse-1.5.0
Odie-F_CKSpiders-1.0.8
notnotnotswipez-MoreCompany-1.8.1
Sligili-More_Emotes-1.3.3
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
Evaisa-LethalThings-0.9.4
Pooble-LCBetterSaves-1.7.3
x753-Mimics-2.4.1
AllToasters-SpectateEnemies-2.3.1
FlipMods-LetMeLookDown-1.0.1
x753-More_Suits-1.4.1
ViViKo-RaymanSuit-1.1.0
TheDeadSnake-Touchscreen-1.1.0
Diversion-MaidOutfitFix-1.1.2
broiiler-inacraft_cosmetics_megapack-1.0.1
TheCursedCompany-The_Cursed_Company-1.0.2
ViViKo-MoreMaterials-1.3.1
rhydiaan-NicerTeleporters-1.1.1
quackandcheese-MirrorDecor-1.3.2
NiaNation-AbsasCosmetics-1.2.3
FlipMods-TooManyEmotes-1.9.5
taffyko-BetterSprayPaint-2.0.2
sunnobunno-YippeeMod-1.2.4
Rune580-LethalCompany_InputUtils-0.6.3
fizzysaur-Happy_Hats-2.0.0
PupVR-Pups_Cute_Cosmetics-1.1.5
Ozone-Runtime_Netcode_Patcher-0.2.5
HGG-JigglePhysicsPlugin-1.1.2
kuba6000-LC_Masked_Fix-0.0.2
AinaVT-LethalConfig-1.3.4
BudgetAirpods-InsanityRemastered-1.1.2
Jordo-NeedyCats-1.2.0
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.2.0
IAmBatby-LethalLevelLoader-1.1.6
BunyaPineTree-ModelReplacementAPI-2.3.8
PXC-ShipLootPlus-1.0.8
ficcialfaint-Spectator_Voice_Icon_Fix-1.0.0
Zaggy1024-OpenBodyCams-1.2.11
EliteMasterEric-Coroner-1.6.0
Skydust-PersistentPurchasesRewritten-1.0.0
EliteMasterEric-SlimeTamingFix-1.0.2
mrov-LethalRichPresence-0.5.8
Bibendi-AEIOUCompany-1.3.6
Zaggy1024-NutcrackerFixes-1.2.2
Bobbie-FixRPCLag-1.0.1
bigmcnugget-VanillaContentExpansion-0.1.8
Nuts-LethalPlushies-1.7.1
Spyci-CozyImprovements-1.2.2
Electric131-IsThisTheWayICame-1.1.4
Caigan-Tokucade_Scrap-1.6.0
tism_club-Movement_Company_Fixed-1.0.2
Zaggy1024-PathfindingLagFix-1.2.1
ShaosilGaming-GeneralImprovements-1.1.11
Verity-TooManySuits-1.0.5
Quixler-DeadAndBored-1.2.0
Suskitech-AlwaysHearActiveWalkies-1.4.4
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
AlexCodesGames-AdditionalContentFramework-1.0.3
Narobic-Simple_Suits-2.1.4
AlexCodesGames-AdditionalSuits-2.0.0
Hexnet111-SuitSaver-1.1.4
BatTeam-LethalFashion-1.0.6
Insomniax-InsomniaxCosmetics-1.2.0
companyemployee-EquipmentCompany-1.3.0
Nyaneko-Nyaneko_Suits-1.1.2
Alice-ScarletDevilMansion-1.2.12
mikegoutokujiii-MikesCosmeticPack-2.0.0
ClifffW-LethalMadness-1.1.0
Vegasx-Female_Scavenger-0.2.0
jaspercreations-Scopophobia-1.1.1
Badham_Mods-SCPFoundationDungeon-3.0.0
Zingar-SecretLabs-3.3.7
FEB-SCP_Suits-1.1.0
OfEden-ScavengerMaid-1.0.0
Lordfirespeed-OdinSerializer-2022.11.9
xilophor-LethalNetworkAPI-2.1.6
Piggy-LC_Office-1.0.24
Hardy-LCMaxSoundsFix-1.1.0
Dantor-Dantors_Mental_Hospital-1.1.0
skidz-PoolRooms-0.1.18
x753-Peepers-0.9.6
loaforc-loaforcsSoundAPI-0.1.3
Bobbie-UniTask-2.5.0
Bobbie-NAudio-2.2.2
qwbarch-BarchLib-1.0.0
qwbarch-Mirage-1.0.16
NomnomAB-RollingGiant-2.5.2
Confusified-KillBind-1.1.3
stormytuna-RouteRandom-1.3.2
stefan750-LCUltrawide-1.1.1
Rozebud-FOV_Adjust-1.1.1
ShaosilGaming-FlashlightFix-1.1.2
FlipMods-ReservedItemSlotCore-1.8.17
FlipMods-ReservedFlashlightSlot-1.6.3
Renegades-FlashlightToggle-1.5.0
FlipMods-ReservedWalkieSlot-1.6.2
mrov-WeatherTweaks-0.4.6
AMRV-ConfigurableCompany-3.0.1
AMRV-LethalCompanyVariables-1.9.0
Fredolx-MeteoMultiplier-1.1.3
LethalMatt-Bozoros-0.1.2
Midge-PushCompany-1.2.0
Solar32-PerformanceEnhancer-1.3.6
IntegrityChaos-LCCutscene-1.0.0
zealsprince-Locker-0.13.1
IntegrityChaos-GraphicsAPI-1.0.0
LethalResonance-LETHALRESONANCE-4.2.2
Kittenji-Groan_Tube_Scrap-1.0.1
Neanderzz-More_Suits_Finii_with_Hat-1.1.0
LethalAPI-LethalAPI_Terminal-1.0.1
IntegrityChaos-Diversity-2.0.3
ViViKo-ItemClippingFix-1.1.4

**Comment by LoafOrc** [comment]
yeah the most specific advice i can give is to remove MoreCompany (that is what is causing the ac warning it seems to do something similar but not the exact same)
other than that just make a new profile and keep going until the issue happens again

**Comment by Catpyre** [comment]
Ahh so mods that allow more than 4 players cause issues?

Also making a new profile unfortunately didn't help, the same missing referenced scripts happen even with morecompany disabled.

**Comment by Catpyre** [comment]
> yeah the most specific advice i can give is to remove MoreCompany (that is what is causing the ac warning it seems to do something similar but not the exact same) other than that just make a new profile and keep going until the issue happens again

I found the issue! I noticed there was al so errors about an elevator missing sound and realized the only mod that adds one in is LC_Office, The errors for Lethal Resonancealso always showed up after LCOffice loads in the logs as well. Disabling LC_Office also fixed the Referenced scripts being missing. I'm not sure how its interacting to cause that though.

**Comment by LoafOrc** [comment]
closing as its related to (mostly) lcoffice. im not sure theres anything that can be done from my side.
