### ISSUE TITLE
Possible Optimisation? FootstepSFXs

### ISSUE THREAD

**Issue by Aeniema** [LoafOrc/loaforcsSoundAPI#7]
Just wondering if this is just standard with the base game or not, but maybe an optimisation could be made where replacements are made for footsfx when movement is detected? Otherwise footsteps are calculated even when a player isn't moving - not an issue, just maybe a possible optimisation. <3

![image](https://github.com/LoafOrc/loaforcsSoundAPI/assets/117127021/f482549c-3075-4b5f-9e57-64baecb27e36)

**Comment by LoafOrc** [comment]
a little late but whatever:
this is probably just an enemy walking around and i'm not going to block that sound from getting replaced by anyone
